[build]
  command = "pnpm run build"
  publish = "dist"

# Redirects for SPA routing (if you add client-side routing later)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"


# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for images
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for PDFs
[[headers]]
  for = "*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Form handling (for your contact form)
[functions]
  # If you want to add serverless functions later
  # directory = "netlify/functions"

# Environment variables (you can override these in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"